### ISSUE TITLE
Please add .cloudwaysapps.com to the staging/dev list.

### ISSUE THREAD

**Issue by wormeyman** [rosswintle/turbo-admin#23]
to be added to `function isTestOrStagingUrl(url) {` I added `url.endsWith('.cloudwaysapps.com') || // Cloudways staging` to line 270ish and that worked for me 👍 .

**Comment by rosswintle** [comment]
Just realised this is still open. It was fixed in the last release of the extension. Closing!

Thanks for the report!!
