### ISSUE TITLE
TurboAdmin on Github.com

### ISSUE THREAD

**Issue by eduwass** [rosswintle/turbo-admin#25]
I've binded TurboAdmin to `cmd` + `k`, funny enough it looks like since:
[https://github.com/wp-admin](https://github.com/wp-admin) `https://github.com/wp-admin` exists.

TurboAdmin is enabled and thus shows up on top of their command palette.

See the video to better understand what I mean:

https://user-images.githubusercontent.com/1070495/220988879-8faee545-817d-437e-9013-352a77403ee7.mp4

PS: This refers to the Chrome Extension of course, so not sure if this repo is the best place to report.

Cheers!

**Comment by rosswintle** [comment]
Thanks for this.

Totally fine to leave issues here - the extension is in a private repo. I wish you could have public issues on private repos. But GitHub doesn't seem to allow that.

Hah. That's kinda funny. Talk about an edge case! How on EARTH did you find this out?

Surely you don't visit the `/wp-admin` repo daily just to see what happens? 🤔 

I'm working on the extension at the moment so I'll get a fix in for this.

**Comment by rosswintle** [comment]
That must be pretty annoying too.

If you want to fix it, and if you trust me to provide arbitrary JavaScript code to run in your console (which you should because it's me, of course, but you shouldn't normally, but also I won't be offended if you don't):

* Go to chrome://extensions
* Find Turbo Admin and click "Inspect views: background page"
* In the console in the devtools box that appears, enter the following three lines:

```
const wphosts = await getWpHosts();
wphosts.splice(wphosts.indexOf('github.com'), 1);
await saveWpHosts(wphosts);
```

This should be pretty self-explanatory if you understand some JavaScript.

Hope that helps.

**Comment by eduwass** [comment]
I don't remember visiting that repo before, actually, I think I went there because TurboAdmin took me there when prompting me to log in (what I show in the video).

I do not have `github.com/wp-admin` in my browser history before today when it all started happening, so I'm not really sure what the hell happened lol.

Thanks for taking the time to share that piece of code. If this happens again I'll let you know... so weird! 🤯

**Comment by rosswintle** [comment]
Oooh, I think I know what happened. I look for `/wp-content` in the URL and assume that if that is present then it's a WP site.

But this also matches things like:

https://github.com/WordPress/WordPress/blob/master/wp-content/index.php

So if you have a WP site in GitHub where you store stuff in `/wp-content` in the repo, then that could trigger it.

Annoying. And a bit stupid on my part.

I'll get it fixed soon, and there will be an automatic removal of github.com from that list too.

**Comment by rosswintle** [comment]
I've added a fix to the extensions. It will be in the next release.

Sorry about this!

**Comment by eduwass** [comment]
No worries at all, thanks for the fix!! 🙏
