### ISSUE TITLE
Bump required WP version down to 4.9.x

### ISSUE THREAD

**Issue by johnalarcon** [rosswintle/turbo-admin#9]
This is a request to take the required version down to 4.9.x so that it will be (fully) compatible with ClassicPress.

As written, the plugin works great on ClassicPress and is fully functional. It looks like the WP requirement of 5.x may have been a nod to the current WP version, rather than a hard requirement. The only issue is that, because ClassicPress is seen as WP 4.9.x, it doesn't get any update notices when you push a new version. Bumping the required version down solves this issue and avoids the fragmentation/confusion that a fork can introduce.

Thanks for considering...and for building this amazing plugin!

**Comment by rosswintle** [comment]
Done in version 1.5.1

**Comment by johnalarcon** [comment]
Thanks again for this. :)
